### PR TITLE
To support Windows 10 Creator update (1703)

### PR DESCRIPTION
**Pull request by danransom**
Fixes the ticket expiration to use UTC

### CODE REVIEW

**Comment by phantomtypist** [comment]
Please see my comments on issue 54 (https://github.com/apereo/dotnet-cas-client/issues/54)

I'd like your thoughts.

**Comment by phantomtypist** [comment]
@hokiecoder FYI I'd like your input too.

**Comment by danransom** [comment]
@phantomtypist works for me

**Comment by hokiecoder** [comment]
This patch looks fine to me and seems more appropriate to only force the UTC time when the service ticket is inserted into the cache manager (in `InsertTicket()`). This seems to be the only place where the expiration time is set for the item in the cache.

However, for transparency and completeness I'd recommend adding comments to explain why the UTC date has to be used here.

**Comment by phantomtypist** [comment]
Please see my comments in issue Please see my comments in issue https://github.com/apereo/dotnet-cas-client/issues/56

**Comment by phantomtypist** [comment]
@danransom @hokiecoder 

Version 1.1.0 has been released to NuGet.org

**Pull request closed without merging**
