### PR TITLE
IServiceTicketManager implementation in .NET 4.5 that leverages EnyimMemcached for ticket storage in a clustered environment

### PR DESCRIPTION
**Pull request by rdev5**
[Couchbase](http://docs.couchbase.com/developer/dev-guide-3.0/memcached.html) supports memcached protocol which this implementation can interface with minimal configuration:

```
<configSections>
  <sectionGroup name="enyim.com">
    <section name="memcached" type="Enyim.Caching.Configuration.MemcachedClientSection, Enyim.Caching" />
  </sectionGroup>
</configSections>


<enyim.com>
  <memcached protocol="Text">
    <servers>
      <add address="127.0.0.1" port="11211" />
    </servers>
  </memcached>
</enyim.com>
```

### CODE REVIEW

**Comment by phantomtypist** [comment]
@rdev5 Would you mind combining this PR into your other one #39 (or vice versa.)  I want to keep them as one logical unit since they are related.

Also, if you could please update your branch from our **develop** branch?

**Comment by TheHokieCoder** [comment]
@phantomtypist Won't this (and the proxy manager) need to be refactored/extracted to be, at the very least, a separate project & NuGet package within the solution? I say that because if it is included automatically we will be introducing and forcing an external dependency (Enyim.Caching) that many will never use. As you mentioned in your RFC (linked above), the goal should be to create additional assemblies/packages that expand the functionality of the base client.

Perhaps there is a way we can create template GitHub projects for proxy and service ticket managers such that we can branch from them to specialize as needed and thus have a better guarantee that they will integrate with the DotNetCasClient correctly? Perhaps I am overthinking it, but it would seem to me that there might be a need for some web.config massaging with this manager as well.

**Comment by phantomtypist** [comment]
Along the lines with which you said, I was envisioning each of these non-in-memory proxy and service ticket managers (as pairs) being in separate repos with separate nuget packages.  e.g. (DotNetCasClient.Redis)

What we have right now in this (main) repo will stay as those are the out-of-the-box provided in-memory ticket providers.  The other repos, for each type of alternative ticket provider, will only contain their specific code.

When you install the nuget package for let's say DotNetCasClient.Memcached (this one) it will just add a reference to your VS project and all you'd have to do is change the namespace/class of the proxy and service ticket managers in the web.config section (already exists and points to the built-in ones.)

At a cursory glance when I looked at the code that wires those things up it looked like this would work.  I think it was just using reflection. If not, worst case, the config file stays the same, but I'd add some dependency injection foo into our code when things get wired-up.

**Comment by phantomtypist** [comment]
On a side note... each of these doesn't _have_ to be in a separate repo.

I could see the benefit of keeping them in separate repos that way we could assign specific contributors to just those specific ticket provider projects.

Otherwise you could keep them all in this repo, but as separate solutions/projects.

Don't get me wrong, I do like the separate repo idea because of what I said two paragraphs up.

**Comment by phantomtypist** [comment]
Yeah, let's do separate repos.  I feel that's the right way.

These nuget packages are going to have different versions and lineage than the main repo.  The CI/CD pipeline is _not_ going to work nicely if they are all in the same repo.

**Comment by TheHokieCoder** [comment]
> At a cursory glance when I looked at the code that wires those things up it looked like this would work. I think it was just using reflection.

This is correct. I'm currently working on my own manager and found that it _does_ work, but when the type is external to the DotNetCasClient assembly, you have to use the "\<type name\>,\<assembly\>" format for the `serviceTicketManager` value. E.g. if you have the type `MemcachedServiceTicketManager` that is compiled into the `DotNetCasClient.Memcached` assembly, you need to use `serviceTicketManager="MemcachedServiceTicketManager,DotNetCasClient.Memcached"` in the web.config file.

I agree that the separate repos is the best way forward, **especially** when the implementations rely on external dependencies. I am thinking of someone proposing a new manager type, we scaffold the new repo for them (that way it stays under the Apereo umbrella), they submit PRs to get it working, and then we can control the building and packaging? Or maybe there is a better way for them to submit a working project and, after validation/testing, incorporate it into the Apereo sphere?

How to best handle this and the proxy manager PR?

**Comment by phantomtypist** [comment]
Worked completed in new repo over at [https://github.com/apereo/dotnet-cas-client-memcached/](https://github.com/apereo/dotnet-cas-client-memcached/)

[DotNetCasClient.Memcached](https://www.nuget.org/packages/DotNetCasClient.Memcached/) NuGet package now available

**Pull request closed without merging**
