### PR TITLE
Fixed stale cookie problem of issue 13.

### PR DESCRIPTION
**Pull request by TheHokieCoder**
More properly stores a forms authentication cookie in both the current HTTP request object and response object in case any code that follows needs to process the data within the cookie. This fixes issue #13.

### CODE REVIEW

**Comment by phantomtypist** [comment]
THAT'S GREAT :|

Now why isn't AppVeyor publishing the artifact to the MyGet ci feed?

**Comment by phantomtypist** [comment]
So weird... I don't see what the deal is.  Nothing present in logs and I can't find anything in the AppVeyor config that says to not deploy on PR's.  There is a setting to not publish to the internal AppVeyor package feed on PR's though.  Two different things, but I guess somehow it's related?

Man, I wish there was something in the logs that explained why and why not things happened.

**Comment by phantomtypist** [comment]
@TheHokieCoder Do you want to give https://www.myget.org/feed/dotnetcasclient-ci/package/nuget/DotNetCasClient/1.2.0-ci-00055 a spin and see if all is good?

**Comment by phantomtypist** [comment]
I'm gonna try and get #62 done tonight or tomorrow and then we can release 1.2.

**Comment by TheHokieCoder** [comment]
@phantomtypist I have tested 1.20-ci-00055 as you suggested and found no adverse effects. I tested with both the Cas20 and Saml11 ticket validators and verified that I still get attributes via the assertion in the SAML response. As far as I can tell (without unit tests), authentication is still working as expected.

**Comment by phantomtypist** [comment]
Nice!

**Comment by phantomtypist** [comment]
Well @TheHokieCoder, I figured out why PR builds on AppVeyor don't get pushed to the MyGet feeds!

http://help.appveyor.com/discussions/questions/1877-how-can-i-deploy-on-public-pull-requests

Looks like AppVeyor doesn't allow it on _public_ repositories.  I don't totally agree with that, but I mean, couldn't they have at least made it a checkbox in the configuration?  Sure, keep what they have has the default, but if I really want I should be able to change that behavior.  In this case it would be fine because it's going to a CI nuget feed.

I _do_ like how they mentioned in one of the comments that they are willing to contemplate allowing the PR build to be deployed if from authorized individuals like you or me.  That feature isn't there yet, but it would solve the problem.

**Pull request merged**
